BUSINESS:
  CP:
    cp_id:
    - 037a3c390f
    - de441ba852
  REST2CP:
    吨每桶: 0.18
    每车收购量范围:
    - 35
    - 44
    比率: 0.9
    180KG桶占比: 1
    收油重量（成品）: 100
  RESTAURANT:
    关键词:
    - 酸菜鱼
    - 小吃
    - 小食
    - 美食
    - 饮食
    - 私房菜
    - 农家菜
    - 快餐
    - 餐饮
    - 汉堡
    - 餐厅
    - 餐馆
    - 饭店
    - 饭馆
    - 川菜
    - 湘菜
    - 农庄
    - 山庄
    - 大排档
    - 食府
    - 酒楼
    - 酒家
    - 烤鱼
    - 猪
    - 手撕大骨
    - 猪杂
    - 牛肉粉
    - 米线
    - 沙拉
    - 抄手
    - 关东煮
    - 酸奶
    - 汤包
    屏蔽词:
    - 熟
    - 鱼生
    - 腌
    - 滑
    - 饼
    - 糕
    - 烧肉
    - 鸡
    - 鹅
    - 鸭
    - 馍
    - 捞
    - 鲜
    - 酸奶
    - 紫燕百味鸡
    - 果
    - 拔戒排骨
    - 馒
    - 奶
    - 商行
    - 士多
    - 汤
    - 品诺（湖南）
    - 燕安居（湖南）
    - 芒
    - 拌
    - 艾
    - 包
    - 小屉鲜
    - 米花
    - 形象设计
    - 书亦
    - 古茗
    - 大卡司
    - 益禾堂
    - 熟食
    - 茶饮
    - 盐焗鸡
    - 早餐
    - 开心花甲
    - 点
    - 熟腌
    - 椰子冻
    - 糯米鸡
    - 碗仔翅
    - 嘉洲鸡
    - 手撕鸡
    - 鸡爪
    - 白切鸡
    - 周黑鸭
    - 煌上煌
    - 肉夹馍
    - 肉泡馍
    - 捆粄
    - 炖品
    - 烧卖
    - 肉卷
    - 猫咖
    - 便当
    - 超市
    - 沙拉
    - 沙律
    - 抄手
    - 钵仔糕
    - 皇上皇
    - 鱼滑
    - 虾滑
    - 饭团
    - 酱香骨
    - 果汁
    - 现捞
    - 关东煮
    - 奶咖
    - 酸奶
    - 豆浆
    - 汤包
    - 士多
    - 奶茶
    - 咖啡
    - 食品
    - 袁记水饺
    - 云吞
    - 面包
    - 饼干
    - 糖水
    - 牛杂
    - 豆腐
    - 麻辣烫
    - 重庆小面
    - 汤圆
    - 烧烤
    - 肉丸
    - 牛肉档
    - 烧腊
    - 凉菜
    - 凉皮
    - 汤粉
    - 鱼档
    - 吐司
    - 轻食
    - 烧鸭
    - 烧鸡
    - 烧肉
    - 烧鹅
    - 烧味
    - 章鱼小丸子
    - 双皮奶
    - 卤味
    - 卤水
    - 小笼包
    - 绝味
    - 包道
    - 馄纯
    - 濑粉
    - 手撕大骨
    - 猪杂
  收油关系映射:
    小食/小吃/美食/饮食/私房菜:
    - 1
    - 2
    酒楼/酒家/烤鱼:
    - 3
    - 4
    酸菜鱼: 1
    餐厅/餐馆/饭店/饭馆/川菜/湘菜/农庄/山庄/大排档/食府/公司/炸鸡:
    - 2
    - 3
    餐饮/汉堡:
    - 1
    - 3
