STREETMAPS:  # 地区街道信息
  huizhou:  # 惠州
    博罗县:
      - 园洲镇
      - 湖镇镇
      - 石坝镇
      - 麻陂镇
      - 龙溪街道
      - 杨侨镇
      - 杨村镇
      - 观音阁镇
      - 龙华镇
      - 柏塘镇
      - 横河镇
      - 罗阳街道
      - 公庄镇
      - 福田镇
      - 长宁镇
      - 泰美镇
      - 石湾镇
    龙门县:
      - 龙华镇
      - 龙田镇
      - 龙江镇
      - 蓝田瑶族乡
      - 永汉镇
      - 龙湮镇
      - 麻榨镇
      - 地派镇
      - 龙城街道
      - 平陵街道
KEYS:  # 整个流程中涉及到的一些apikeys
  kimi_keys: # 调用大模型的keys
    - 'xxxx'
    - 'xxxx'
  baidu_keys: # 百度地图的keys
    - '12345678'
    - '87654321'
  gaode_keys: # 高德地图的keys
    - '12345678'
    - '87654321'
  serp_keys: # serp的keys
    - '12345678'
    - '87654321'
  tripadvisor_keys: # tripadvisor的keys
    - '12345678'
    - '87654321'
  oss:  # 云端服务器的配置项目
    access_key_id: 'exampleAccessKeyId' # exampleAccessKeyId
    access_key_secret: 'exampleAccessKeySecret' #exampleAccessKeySecret
    endpoint: 'http://oss-cn-shanghai.aliyuncs.com'
    bucket_name: 'moco-data'
    region: 'cn-shanghai'
SPECIAL:  # 凡是在这里面的将被添加到后面Config类的special_list中，将在前段显示
  - KEYS.oss
  - KEYS.kimi_keys